angular.module("sequenceRouter",[]).config(function ($routeProvider){
	$routeProvider.when("/",{
		templateUrl:"/contentSequenceDashboard.html",
		controller:"sequenceControllerMain"
	})
	.when("/dashboard/sequence",{
		templateUrl:"/contentSequenceDashboard.html",
		controller:"sequenceControllerMain"
	})
	.when("/sequence/layouts",{
		templateUrl:"/contentSequenceLayouts.html",
		controller:"sequenceControllerLayouts"
	})
	.when("/sequence/lista",{
		templateUrl:"/contentSequenceLista.html",
		controller:"sequenceControllerLista"
	})
	.when("/sequence/servicos",{
		templateUrl:"/contentSequenceServicos.html",
		controller:"sequenceControllerService"
	})
	.when("/sequence/configuracao",{
		templateUrl:"/contentSequenceConfiguracao.html",
		controller:"sequenceControllerConfig"
	})
	.when("/404",{
		templateUrl:"/404in.html",
		controller:"sequenceControllerMain"
	})
	.otherwise({
		redirectTo:"/404"
	});
});